/////////////////////////////////////////////////////////////////////////////
/// Class:       CRTSimHitProducer
/// Module Type: producer
/// File:        CRTSimHitProducer_module.cc
///
/// Producer module for constructing CRTHits from simulated CRT data
///
/// Author:         Thomas Brooks
/// E-mail address: tbrooks@fnal.gov
/////////////////////////////////////////////////////////////////////////////

// sbndcode includes
#include "sbnobj/SBND/CRT/CRTData.hh"
#include "sbnobj/Common/CRT/CRTHit.hh"
#include "sbndcode/CRT/CRTUtils/CRTHitRecoAlg.h"

// Framework includes
#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Event.h" 
#include "canvas/Persistency/Common/Ptr.h" 
#include "canvas/Persistency/Common/PtrVector.h" 
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art_root_io/TFileService.h"
#include "art_root_io/TFileDirectory.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "canvas/Persistency/Common/FindManyP.h"
#include "art/Persistency/Common/PtrMaker.h"

#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include <memory>
#include <iostream>
#include <map>
#include <iterator>
#include <algorithm>

// LArSoft
#include "lardataobj/Simulation/SimChannel.h"
#include "lardataobj/Simulation/AuxDetSimChannel.h"
#include "larcore/Geometry/Geometry.h"
#include "larcore/Geometry/AuxDetGeometry.h"
#include "larcorealg/Geometry/GeometryCore.h"
#include "larcorealg/Geometry/PlaneGeo.h"
#include "larcorealg/Geometry/WireGeo.h"
#include "lardataobj/RecoBase/OpFlash.h"
#include "lardata/Utilities/AssociationUtil.h"
#include "lardata/DetectorInfoServices/LArPropertiesService.h"
#include "lardata/DetectorInfoServices/DetectorPropertiesService.h"
#include "lardata/DetectorInfoServices/DetectorClocksService.h"
#include "lardataobj/RawData/ExternalTrigger.h"
#include "larcoreobj/SimpleTypesAndConstants/PhysicalConstants.h"
#include "larcoreobj/SimpleTypesAndConstants/geo_types.h"

// ROOT
#include "TTree.h"
#include "TFile.h"
#include "TH1D.h"
#include "TH2D.h"
#include "TVector3.h"
#include "TGeoManager.h"


namespace sbnd {
  
  class CRTSimHitProducer : public art::EDProducer {
  public:

    explicit CRTSimHitProducer(fhicl::ParameterSet const & p);

    // The destructor generated by the compiler is fine for classes
    // without bare pointers or other resource use.

    // Plugins should not be copied or assigned.
    CRTSimHitProducer(CRTSimHitProducer const &) = delete;
    CRTSimHitProducer(CRTSimHitProducer &&) = delete;
    CRTSimHitProducer & operator = (CRTSimHitProducer const &) = delete; 
    CRTSimHitProducer & operator = (CRTSimHitProducer &&) = delete;

    // Required functions.
    void produce(art::Event & e) override;

    // Selected optional functions.
    void beginJob() override;

    void endJob() override;

    void reconfigure(fhicl::ParameterSet const & p);

    void FillThreeDTree(const art::Event &event, const std::vector<std::pair<sbn::crt::CRTHit, std::vector<int>>> &crtHitPairs, 
			const std::vector<art::Ptr<sbnd::crt::CRTData>> &crtList, const art::Handle< std::vector<sbnd::crt::CRTData>> &crtListHandle);
    
    void ResetData();


  private:

    // Params from fcl file.......
    art::InputTag fCrtModuleLabel;      ///< name of crt producer
   
    CRTHitRecoAlg hitAlg;

    TTree *fHitTree, *fThreeDHitTree;

    float tPEsHit, tPosX, tPosY, tPosZ, tErrX, tErrY, tErrZ;
    unsigned tTime, nIDEs;
    std::string tTagger;
    std::vector<double> tEntryX, tEntryY, tEntryZ, tEntryT, tExitX, tExitY, tExitZ, tExitT;

  }; // class CRTSimHitProducer


  CRTSimHitProducer::CRTSimHitProducer(fhicl::ParameterSet const & p)
  : EDProducer(p), hitAlg(p.get<fhicl::ParameterSet>("HitAlg"))
  // Initialize member data here, if know don't want to reconfigure on the fly
  {

    // Call appropriate produces<>() functions here.
    produces< std::vector<sbn::crt::CRTHit> >();
    produces< art::Assns<sbn::crt::CRTHit , sbnd::crt::CRTData> >();
    
    reconfigure(p);

    art::ServiceHandle<art::TFileService> tfs;
    fHitTree = tfs->make<TTree>("HitTree","CRT Strip Hit Tree");
    fThreeDHitTree = tfs->make<TTree>("ThreeDHitTree","ThreeD CRT Hit Tree");

  } // CRTSimHitProducer()


  void CRTSimHitProducer::reconfigure(fhicl::ParameterSet const & p)
  {

    fCrtModuleLabel       = (p.get<art::InputTag> ("CrtModuleLabel")); 

  } // CRTSimHitProducer::reconfigure()


  void CRTSimHitProducer::beginJob()
  {
    std::vector<std::string> tStripName;
    std::vector<unsigned> tChannel, tPulseT0, tPulseT1, tPulseADC;
    double tPE1, tPE2;
    std::string tTaggerName;
    std::vector<double> tStripTrueMin, tStripTrueMax;
    unsigned tPlane;
    double tHitT0, tHitX, tHitXErr, tHitPEs;
    std::vector<double> tLimits;
    unsigned nOneDIDEs;
    std::vector<double> tOneDEntryX, tOneDEntryY, tOneDEntryZ, tOneDEntryT, tOneDExitX, tOneDExitY, tOneDExitZ, tOneDExitT;

    fHitTree->Branch("StripName",&tStripName);
    fHitTree->Branch("Channel",&tChannel);
    fHitTree->Branch("PulseT0",&tPulseT0);
    fHitTree->Branch("PulseT1",&tPulseT1);
    fHitTree->Branch("PulseADC",&tPulseADC);
    fHitTree->Branch("PE1",&tPE1);
    fHitTree->Branch("PE2",&tPE2);
    fHitTree->Branch("StripTrueMin",&tStripTrueMin);
    fHitTree->Branch("StripTrueMax",&tStripTrueMax);
    fHitTree->Branch("TaggerName",&tTaggerName);
    fHitTree->Branch("Plane",&tPlane);
    fHitTree->Branch("HitT0",&tHitT0);
    fHitTree->Branch("HitX",&tHitX);
    fHitTree->Branch("HitXErr",&tHitXErr);
    fHitTree->Branch("HitPEs",&tHitPEs);
    fHitTree->Branch("Limits",&tLimits);
    fHitTree->Branch("nIDEs",&nOneDIDEs);
    fHitTree->Branch("EntryX",&tOneDEntryX);
    fHitTree->Branch("EntryY",&tOneDEntryY);
    fHitTree->Branch("EntryZ",&tOneDEntryZ);
    fHitTree->Branch("EntryT",&tOneDEntryT);
    fHitTree->Branch("ExitX",&tOneDExitX);
    fHitTree->Branch("ExitY",&tOneDExitY);
    fHitTree->Branch("ExitZ",&tOneDExitZ);
    fHitTree->Branch("ExitT",&tOneDExitT);

    fThreeDHitTree->Branch("PEsHit",&tPEsHit);
    fThreeDHitTree->Branch("PosX",&tPosX);
    fThreeDHitTree->Branch("PosY",&tPosY);
    fThreeDHitTree->Branch("PosZ",&tPosZ);
    fThreeDHitTree->Branch("ErrX",&tErrX);
    fThreeDHitTree->Branch("ErrY",&tErrY);
    fThreeDHitTree->Branch("ErrZ",&tErrZ);
    fThreeDHitTree->Branch("Time",&tTime);
    fThreeDHitTree->Branch("tTagger",&tTagger);
    fThreeDHitTree->Branch("nIDEs",&nIDEs);
    fThreeDHitTree->Branch("EntryX",&tEntryX);
    fThreeDHitTree->Branch("EntryY",&tEntryY);
    fThreeDHitTree->Branch("EntryZ",&tEntryZ);
    fThreeDHitTree->Branch("EntryT",&tEntryT);
    fThreeDHitTree->Branch("ExitX",&tExitX);
    fThreeDHitTree->Branch("ExitY",&tExitY);
    fThreeDHitTree->Branch("ExitZ",&tExitZ);
    fThreeDHitTree->Branch("ExitT",&tExitT);

  } // CRTSimHitProducer::beginJob()


  void CRTSimHitProducer::produce(art::Event & event)
  {

    std::unique_ptr< std::vector<sbn::crt::CRTHit> > CRTHitcol( new std::vector<sbn::crt::CRTHit>);
    std::unique_ptr< art::Assns<sbn::crt::CRTHit, sbnd::crt::CRTData> > Hitassn( new art::Assns<sbn::crt::CRTHit, sbnd::crt::CRTData>);
    art::PtrMaker<sbn::crt::CRTHit> makeHitPtr(event);

    int nHits = 0;

    // Retrieve list of CRT hits
    art::Handle< std::vector<sbnd::crt::CRTData>> crtListHandle;
    std::vector<art::Ptr<sbnd::crt::CRTData> > crtList;
    if (event.getByLabel(fCrtModuleLabel, crtListHandle))
      art::fill_ptr_vector(crtList, crtListHandle);

    auto const clockData = art::ServiceHandle<detinfo::DetectorClocksService const>()->DataFor(event);
    auto const detProp = art::ServiceHandle<detinfo::DetectorPropertiesService const>()->DataFor(event, clockData);
    // Fill a vector of pairs of time and width direction for each CRT plane
    // The y crossing point of z planes and z crossing point of y planes would be constant
    std::map<std::pair<std::string, unsigned>, std::vector<CRTStrip>> taggerStrips = hitAlg.CreateTaggerStrips(clockData, detProp, crtList, crtListHandle, event, fHitTree);

    mf::LogInfo("CRTSimHitProducer")
      <<"Number of SiPM hits = "<<crtList.size();

    std::vector<std::pair<sbn::crt::CRTHit, std::vector<int>>> crtHitPairs = hitAlg.CreateCRTHits(taggerStrips);

    for(auto const& crtHitPair : crtHitPairs){
      CRTHitcol->push_back(crtHitPair.first);
      art::Ptr<sbn::crt::CRTHit> hitPtr = makeHitPtr(CRTHitcol->size()-1);
      nHits++;
      for(auto const& data_i : crtHitPair.second){
        Hitassn->addSingle(hitPtr, crtList[data_i]);
      }
    }
      

    event.put(std::move(CRTHitcol));
    event.put(std::move(Hitassn));

    mf::LogInfo("CRTSimHitProducer")
      <<"Number of CRT hits produced = "<<nHits;

    FillThreeDTree(event, crtHitPairs, crtList, crtListHandle);
    
  } // CRTSimHitProducer::produce()

  void CRTSimHitProducer::FillThreeDTree(const art::Event &event, const std::vector<std::pair<sbn::crt::CRTHit, std::vector<int>>> &crtHitPairs, 
					 const std::vector<art::Ptr<sbnd::crt::CRTData>> &crtList, const art::Handle< std::vector<sbnd::crt::CRTData>> &crtListHandle)
  {
    for(auto const &[crtHit, dataIDs] : crtHitPairs)
      {
	ResetData();
	tPEsHit = crtHit.peshit;
	tPosX = crtHit.x_pos;
	tPosY = crtHit.y_pos;
	tPosZ = crtHit.z_pos;
	tErrX = crtHit.x_err;
	tErrY = crtHit.y_err;
	tErrZ = crtHit.z_err;
	tTime = crtHit.ts0_ns;
	tTagger = crtHit.tagger;

	art::FindManyP<sim::AuxDetIDE> dataToIDEsAssn(crtListHandle, event, "crt");
	
	for(auto const &dataID : dataIDs)
	  {
	    std::vector<art::Ptr<sim::AuxDetIDE>> ides = dataToIDEsAssn.at(crtList[dataID].key());

	    for(auto const &ide : ides)
	      {
		++nIDEs;
		tEntryX.push_back(ide->entryX);
		tEntryY.push_back(ide->entryY);
		tEntryZ.push_back(ide->entryZ);
		tEntryT.push_back(ide->entryT);
		tExitX.push_back(ide->exitX);
		tExitY.push_back(ide->exitY);
		tExitZ.push_back(ide->exitZ);
		tExitT.push_back(ide->exitT);
	      }
	  }
	fThreeDHitTree->Fill();
      }
  }

  void CRTSimHitProducer::ResetData()
  {
    tPEsHit = -999999.f; tPosX = -999999.f; tPosY = -999999.f; tPosZ = -999999.f;
    tErrX = -999999.f; tErrY = -999999.f; tErrZ = -999999.f;
    tTime = 999999;
    tTagger = "";
    nIDEs = 0;
    tEntryX.clear(); tEntryY.clear(); tEntryZ.clear(); tEntryT.clear();
    tExitX.clear(); tExitY.clear(); tExitZ.clear(); tExitT.clear();
  }

  void CRTSimHitProducer::endJob()
  {

  } // CRTSimHitProducer::endJob()


  DEFINE_ART_MODULE(CRTSimHitProducer)

} // sbnd namespace
